POST http://localhost:8080/auth/signup HTTP/1.1
content-type: application/json

{
    "email": "s",
    "password": "1",
    "fistName": "asd",
    "secondName": "zxc",
    "lastName": "asczxc"
}
###
POST http://localhost:8080/auth/signin HTTP/1.1
content-type: application/json

{
    "email": "s",
    "password": "1",
    "fistName": "asd",
    "secondName": "zxc",
    "lastName": "asczxc"
}
###
GET http://localhost:8080/auth/signout HTTP/1.1
